server:
  port: 8085

planets:
  filter: 'http://localhost:8080/api/planets'

starships:
  filter: 'http://localhost:8081/api/starships'


spring:
  data:
    mongodb:
      database: planets-db
#      host: mongodb
      host: localhost

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

