server:
  port: 8085

planets:
  filter: 'http://10.5.0.10:8080/api/planets'

starships:
  filter: 'http://10.5.0.5:8081/api/starships'


#spring:
#  data:
#    mongodb:
#      database: banco
#      host: localhost
#      port: 27017

spring:
  data:
    mongodb:
      database: planets-db
      host: mongodb

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

