server:
  port: 8085

planets:
  filter: 'http://localhost:8080/api/planets'

starships:
  filter: 'http://localhost:8081/api/starships'

spring:
  data:
    mongodb:
      database: banco
      host: localhost
      port: 27017